### ISSUE TITLE
The method of inputting the parameter is incorrect.

### ISSUE THREAD

**Issue by annie-jpg** [djoshea/matlab-barplot#1]
error use AutoAxis
error: file: AutoAxis.m row: 6571 column: 131
The use of the '=' operator is incorrect. To assign a value to a variable, use '='. To compare values for equality, use '=='.

eg :
ax.addAnchor(AnchorInfo(h, PositionType.Left, hto, PositionType.Left, padding(1), desc + " (left)", translateDontScale=true));
should fix to:
ax.addAnchor(AnchorInfo(h, PositionType.Left, hto, PositionType.Left, padding(1), desc + " (left)", 'translateDontScale',true));

**Comment by djoshea** [comment]
Hi annie-jpg, 

This `keyword=value` Python-like syntax is supported in Matlab R2021a and since I switch back and forth, I prefer it to the old `'keyword', value` syntax. I haven't been particularly careful about noting required versions since I generally use the most recent available, so I see how this could create issues for other people using the code. My apologies. I haven't changed old code to use the new syntax, but most of my new code does use the new syntax.

https://www.mathworks.com/help/matlab/matlab_prog/namevalue-in-function-calls.html

Thanks!
